### PR TITLE
Refactor docker-build-ami to make it easier to test and expand on

### PR DESCRIPTION
**Pull request by jamieleecho**
This pull request refactors docker-build-ami to make it easier to test and expand on.

It adds the following:
* Refactors logic to separate parsing, state management and communicating with AWS
* Adds a test harness with substantial test coverage
* Adds travis-ci support
* Uses more python3 features and conventions

### CODE REVIEW

**Comment by jamieleecho** [comment]
Hey @mickep76 thank you for putting together `docker-build-ami` - it is a nice mechanism to help transition between Dockerfiles and EC2.

The goal of this Pull Request is to make it a little easier to maintain by adding unit tests - this makes it a bit easier to test components separately without having to go through the whole AMI creation process. I hope it does achieve this goal - please let me know what your thoughts are.

**Comment by ake-persson** [comment]
This is much appreciated, I haven't touched this code base in ages. You're more qualified to maintain this atm. So I will go ahead and merge this and make you an admin for the project.

**Comment by ake-persson** [comment]
I'll see if I can spend some time and get the Travis test's running for each commit and publish the changes to PyPi.

**Comment by ake-persson** [comment]
It'll take me some time to mind-meld this since I haven't touched Python for the last 4 years since I'm a Go fanboy these days. But this as good reason as any to refresh those skills ;D

Then I'll give you some proper feedback.

**Comment by jamieleecho** [comment]
Thank you for the quick turnaround! Integrating the pypy upload into Travis would be great!

**Pull request merged**
